server:
  port: 8800

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  file-upload-path: /home/wang/webStack-Guns/file/    #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.jsnjfz.manage.modular.system.model

log:
  path: manage-logs

sftp:
  host: 47.99.97.8
  username: ENC(nwwXRJMTVEcyqwOmqk/Rig==)
  password: ENC(JK0jAODKzWIQSrbU8s+hICIV461++Squ)
  port: 22

jasypt:
  encryptor:
    # 指定解密算法，需要和加密时使用的算法一致
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://47.99.97.8:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(RtATcFe1bZ1znf2/yl2bbjb3sRG/i/JB)
    password: ENC(4lMH+P4ZNKfYnUKEB5V5OpFQF7210EgRyPRoWsuyjIo=)
    filters: wall,mergeStat



